os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: C:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GOPATH: C:\gopath
    CC: gcc.exe
  matrix:
    - GETH_ARCH: amd64
      MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      PATH: C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;%PATH%

install:
  - git submodule update --init
  - rmdir C:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.10.3.windows-%GETH_ARCH%.zip
  - 7z x go1.10.3.windows-%GETH_ARCH%.zip -y -oC:\ > NUL
  - go version
  - gcc --version

build_script:
  - go run build\ci.go install
  - 7z a multi-geth-win64-%APPVEYOR_REPO_TAG_NAME%.zip .\build\bin\geth.exe

#test_script:
  #- set CGO_ENABLED=1
  #- go run build\ci.go test

artifacts:
  - path: '*.zip'
    name: geth

deploy:
  artifact: /multi-geth-win64-%APPVEYOR_REPO_TAG_NAME%\.zip.*/
  auth_token:
    secure: OzaYbBXj6g9odl/p+gGOXOBrT9AXCmNWxeyyDetSY66CWMxEzgUT2fO/Hr0ODFxe
  draft: true
  on:
    appveyor_repo_tag: true
  provider: GitHub
